# Generated by Django 5.2.1 on 2025-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('supervisor_name', models.CharField(blank=True, max_length=100)),
                ('experience_rating', models.CharField(max_length=20)),
                ('skills_learned', models.TextField()),
                ('overall_satisfaction', models.IntegerField()),
                ('suggestions', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
